# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-20.04" ]
        #        python-version: [ "3.6.2", "3.7", "3.8", "3.9" ]
        python-version: [ "3.8" ]
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      #----------------------------------------------
      #  -----  install dependencies  -----
      #----------------------------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

      #----------------------------------------------
      # check codestyle & lint
      #----------------------------------------------
      - name: Check codestyle
        run: |
          make check-codestyle
      - name: Lint with flake8
        run: |
          make lint
      - name: Type check
        run: |
          make type
      #----------------------------------------------
      #  -----  install & configure ROS  -----
      #----------------------------------------------
      # - name: install ROS
      #   run: |
      #     sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
      #     sudo apt install curl # if you haven't already installed curl
      #     curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
      #     sudo apt update
      #     sudo apt install ros-noetic-ros-base
      #     echo "source /opt/ros/noetic/setup.bash" >> .venv/bin/activate
      #     sudo apt-get install ros-noetic-cv-bridge
      # #----------------------------------------------
      # #    add matrix specifics and run test suite
      # #----------------------------------------------
      # - name: Run tests
      #   run: |
      #     source .venv/bin/activate
      #     make pytest
